### ISSUE TITLE
set_contents() method of ktk.Player is inconsistent, produces white screen plot

### ISSUE THREAD

**Issue by zybermonk** [kineticstoolkit/kineticstoolkit#257]
**Describe the bug**
The `set_contents()` method produces an empty white plot called 'Figure1'

**To Reproduce**
1. Load data as usual : 
```
filename = ktk.doc.download("kinematics_tennis_serve_2players.c3d")
markers = ktk.read_c3d(filename)["Points"]
```
2. Create a player and set_contents, the behaviour works as usual with the required animation with:
```
p1 = ktk.Player()
p1.set_contents(markers)
```
![image](https://github.com/user-attachments/assets/774eb762-92ca-460a-aaea-0e4bf99e48f7)

3. Load the data in the player into a variable using `get_contents`, alter or do not alter the variable, irrespectively, upon applying `set_contents` to the player again with this data,
```
temp_markers = p1.get_contents()
p1.set_contents(temp_markers)
```
The following result is obtained:
4. See error:
![image](https://github.com/user-attachments/assets/7b772265-db42-4474-b036-ced4e3ecffbb)

**Expected behavior**
`set_contents()` only works once?. That assumption was also wrong as it does not work even if the player is initialized as `p1 = ktk.Player(markers)` . But when the same data is used in a new player, the plot is obtained correctly, for example: `p2 = ktk.Player(temp_markers)` works well.

**Comment by felixchenier** [comment]
Thanks @zybermonk for the detailed reproduction steps.
This is not the expected behaviour, I'll have a look at it.

**Comment by felixchenier** [comment]
Hi @zybermonk 

Unfortunately I can't reproduce this bug, all works as expected. Could you tell me this information please:

- Your OS:
- Your OS version:
- Your KTK version: `import kineticstoolkit as ktk; print(ktk.config.version)`
- Your Python version:

Thanks

**Comment by zybermonk** [comment]
Hi @felixchenier 

**OS:**
Description:    Ubuntu 20.04.6 LTS
Codename:       focal

**Python:**
Python 3.12.5

**KTK:**
kineticstoolkit    0.14.3
numpy              2.1.0

I could not directly import ktk due to the error:
AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

So my workaround was not downgrading numpy but the following;
```
def import_ktk():

    np.Inf = np.inf
    import kineticstoolkit.lab as ktk
    del np.Inf
    return ktk

ktk = import_ktk()
```

**Comment by felixchenier** [comment]
OK thanks. There's a newer version of KTK (0.15) that fixes this problem with NumPy 2 and that should also fix your need for this workaround. Could you see if simply upgrading KTK to this version fixes it?

```
conda upgrade kineticstoolkit
```

**Comment by zybermonk** [comment]
@felixchenier The bug seems to be fixed now. Thanks you for the assistance.
